version: "3.3"

services:
  nginx:
    image: nginx
    container_name: test_proxy
    labels:
      - "traefik.enable=true" # enables the service
      - "traefik.http.routers.nginx.rule=Host(`proxy.localhost.test`)" # domain to expose on
#      - "traefik.http.routers.nginx.entrypoints=web" # if you named your 443 entrypoint differently than 'webscure', substitute it here!
#      - "traefik.http.routers.nginx.tls.certresolver=letsencrypt" # if you named your cert resolver differently than letsencrypt, substitute it here!
    networks:
      - traefik-global-proxy # Traefik network! If you named it differently, substitute it here and below.

networks:
  traefik-global-proxy:
    external: true